# Generated by Django 5.1.4 on 2024-12-17 21:21

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='RU', verbose_name='Номер телефона')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название салона')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес салона')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.FloatField(verbose_name='Цена услуги')),
                ('duration', models.IntegerField(verbose_name='Длительность услуги, мин')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('type_service', models.CharField(max_length=50, verbose_name='Вид услуги')),
                ('work_experience_years', models.IntegerField(default=0, verbose_name='Стаж (годы)')),
                ('work_experience_months', models.IntegerField(default=0, verbose_name='Стаж (месяцы)')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('cancel', 'Отменено')], default='waiting', max_length=14, verbose_name='Статус заказа')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма заказа')),
                ('receipt', models.URLField(blank=True, verbose_name='Чек')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Счёт выставлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Принято'), ('ended', 'Завершено'), ('discard', 'Отменено')], default='accepted', max_length=9, verbose_name='Статус заказа')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('start_at', models.TimeField(verbose_name='Время начала')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.client', verbose_name='Клиент')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.order', verbose_name='Заказ')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.salon', verbose_name='Салон')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service', verbose_name='Услуга')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.specialist', verbose_name='Специалист')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistWorkDayInSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workday', models.DateField(verbose_name='Дата рабочего дня')),
                ('start_at', models.TimeField(verbose_name='Начало рабочего дня')),
                ('end_at', models.TimeField(verbose_name='Окончание рабочего дня')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workdays', to='services.salon', verbose_name='Салон')),
                ('services', models.ManyToManyField(to='services.service', verbose_name='Услуги')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workdays', to='services.specialist', verbose_name='Специалист')),
            ],
        ),
    ]
