# Generated by Django 5.1.4 on 2024-12-17 21:52

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Заказ услуги', 'verbose_name_plural': 'Заказ услуг'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Счет оплаты', 'verbose_name_plural': 'Счета оплаты'},
        ),
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'Салон', 'verbose_name_plural': 'Салоны'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AlterModelOptions(
            name='specialistworkdayinsalon',
            options={'verbose_name': 'Рабочий день', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='Номер телефона'),
        ),
    ]
