# Generated by Django 5.1.4 on 2024-12-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_appointment_options_alter_client_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="image",
            field=models.ImageField(
                blank=True,
                db_index=True,
                upload_to="salon_images/",
                verbose_name="Баннер салона",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                db_index=True,
                upload_to="service_images/",
                verbose_name="Банер услуги",
            ),
        ),
        migrations.AddField(
            model_name="specialist",
            name="image",
            field=models.ImageField(
                blank=True,
                db_index=True,
                upload_to="specialist_images/",
                verbose_name="Фото мастера",
            ),
        ),
    ]
