# Generated by Django 5.1.4 on 2024-12-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_salon_image_service_image_specialist_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialist",
            name="type_service",
        ),
        migrations.AddField(
            model_name="specialist",
            name="position",
            field=models.CharField(max_length=50, verbose_name="Специальность"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specialist",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="specialists",
                to="services.service",
                verbose_name="Вид услуги",
            ),
        ),
    ]
