# Generated by Django 5.1.4 on 2024-12-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0004_remove_specialist_type_service_specialist_position_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.IntegerField(verbose_name="Цена услуги"),
        ),
    ]
