# Generated by Django 5.1.4 on 2024-12-18 18:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона')),
                ('question', models.CharField(blank=True, max_length=300, null=True, verbose_name='Вопрос')),
                ('consulted', models.BooleanField(default=False, verbose_name='Проконсультирован')),
            ],
            options={
                'verbose_name': 'Консультация',
            },
        ),
    ]
