# Generated by Django 5.1.4 on 2024-12-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_consultation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультация'},
        ),
    ]
