# Generated by Django 5.1.4 on 2024-12-19 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_servicecategory_service_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workers",
                to="services.salon",
                verbose_name="Салон",
            ),
        ),
    ]
