# Generated by Django 5.1.4 on 2024-12-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_consultation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['consulted', 'name'], 'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультация'},
        ),
    ]
